config/routes.rb
Rails.application.routes.draw do
  get 'business_types/show_vendors'

  resources :business_types
  resources :vendors

end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base

	has_many :vendor_business_types
	has_many :vendors, through: :vendor_business_types
	validates_presence_of :name, :tin_number, :business_type
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base


	has_many :vendor_business_types
	has_many :business_types, through: :vendor_business_types
	validates_presence_of :first_name, :last_name, :phone_number, :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/vendor_business_type.rb
class VendorBusinessType < ActiveRecord::Base

	belongs_to :vendor
	belongs_to :business_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/business_types_controller.rb
class BusinessTypesController < ApplicationController
  before_action :set_business_type, only: [:show, :edit, :update, :destroy], except: [:show_vendors]

  # GET /business_types
  # GET /business_types.json
  def index
    @business_types = BusinessType.all
  end

  # GET /business_types/1
  # GET /business_types/1.json
  def show
  end

  # GET /business_types/new
  def new
    @business_type = BusinessType.new
  end

  # GET /business_types/1/edit
  def edit
  end

  # POST /business_types
  # POST /business_types.json
  def create
    @business_type = BusinessType.new(business_type_params)

    respond_to do |format|
      if @business_type.save
        format.html { redirect_to @business_type, notice: 'Business type was successfully created.' }
        format.json { render :show, status: :created, location: @business_type }
      else
        format.html { render :new }
        format.json { render json: @business_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_types/1
  # PATCH/PUT /business_types/1.json
  def update
    respond_to do |format|
      if @business_type.update(business_type_params)
        format.html { redirect_to @business_type, notice: 'Business type was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_type }
      else
        format.html { render :edit }
        format.json { render json: @business_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_types/1
  # DELETE /business_types/1.json
  def destroy
    @business_type.destroy
    respond_to do |format|
      format.html { redirect_to business_types_url, notice: 'Business type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_vendors
    @business_type = BusinessType.find(params[:business_type_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_type
      @business_type = BusinessType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_type_params
      params.require(:business_type).permit(:name, :tin_number, :business_type)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    if params[:search]
      @vendors = Vendor.where('first_name LIKE ?', "%#{params[:search]}%")
    else
      @vendors = Vendor.all
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:first_name, :last_name, :email, :phone_number,:business_type_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_types_helper.rb
module BusinessTypesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/business_types/_form.html.erb
<%= form_for(@business_type) do |f| %>
  <% if @business_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_type.errors.count, "error") %> prohibited this business_type from being saved:</h2>

      <ul>
      <% @business_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tin_number %><br>
    <%= f.text_field :tin_number %>
  </div>
  <div class="field">
    <%= f.label :business_type %><br>
    <%= f.text_field :business_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_types/edit.html.erb
<h1>Editing Business Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_type %> |
<%= link_to 'Back', business_types_path %>

app/views/business_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Business Types</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tin number</th>
      <th>Business type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_types.each do |business_type| %>
      <tr>
        <td><%= business_type.name %></td>
        <td><%= business_type.tin_number %></td>
        <td><%= business_type.business_type %></td>
        <td><%= link_to 'Show', business_type %></td>
        <td><%= link_to 'Edit', edit_business_type_path(business_type) %></td>
        <td><%= link_to 'Destroy', business_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show Vendors', business_types_show_vendors_path(:business_type_id => business_type) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business type', new_business_type_path %>

app/views/business_types/new.html.erb
<h1>New Business Type</h1>

<%= render 'form' %>

<%= link_to 'Back', business_types_path %>

app/views/business_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business_type.name %>
</p>

<p>
  <strong>Tin number:</strong>
  <%= @business_type.tin_number %>
</p>

<p>
  <strong>Business type:</strong>
  <%= @business_type.business_type %>
</p>

<%= link_to 'Edit', edit_business_type_path(@business_type) %> |
<%= link_to 'Back', business_types_path %>

app/views/business_types/show_vendors.html.erb
<h2>Listing Vendors </h2>
<% @business_type.vendors.each do |vendor| %>
	<li><%= vendor.first_name %>
	<%= link_to 'Edit', edit_vendor_path(vendor) %> </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VendorManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>

  <% if @vendor.errors.any? %>
    <h2>The errors prohibitted from being created are: </h2>
    <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :business_type_ids %><br>
    <%= f.collection_check_boxes :business_type_ids, BusinessType.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vendors</h1>

<%= form_tag vendors_path, method: :get do %>
  <label>Search : </label>
  <%= text_field_tag :search %>

  <%= submit_tag "Search" %>
<% end %>

<table border="1">
  <thead>
    <tr>
      <th>FirstName</th>
      <th>LastName</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.first_name %></td>
        <td><%= vendor.last_name %></td>
        <td><%= vendor.email %></td>
        <td><%= vendor.phone_number %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>FirstName:</strong>
  <%= @vendor.first_name %>
</p>

<p>
  <strong>LastName:</strong>
  <%= @vendor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vendor.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @vendor.phone_number %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>